In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.1


In [33]:
a = np.random.rand(2,3,5)

In [34]:
print(a)

[[[0.14191737 0.00136571 0.39849946 0.16524998 0.54878359]
  [0.17309166 0.58862771 0.18905959 0.06573976 0.69160061]
  [0.81519098 0.11541216 0.04612078 0.75058299 0.46441832]]

 [[0.83346164 0.54582124 0.49915563 0.12308266 0.32154751]
  [0.9833765  0.20799656 0.06193473 0.04242374 0.71927731]
  [0.8431568  0.36658233 0.66536669 0.73276077 0.57510144]]]


In [35]:
b = np.random.rand(5,3,2)

In [36]:
print(b)

[[[0.17791149 0.51945375]
  [0.21772652 0.39568867]
  [0.19121591 0.83955476]]

 [[0.94633021 0.48474529]
  [0.42135333 0.60637074]
  [0.8368353  0.46675616]]

 [[0.2796681  0.20487417]
  [0.95384687 0.46831543]
  [0.78370585 0.40904908]]

 [[0.44667648 0.1547462 ]
  [0.56420505 0.9719901 ]
  [0.18859865 0.64007073]]

 [[0.70465043 0.5961797 ]
  [0.76072129 0.95531086]
  [0.23311596 0.69518354]]]


In [37]:
a.shape == b.shape

False

In [38]:
c = b.T

In [39]:
print(c)

[[[0.17791149 0.94633021 0.2796681  0.44667648 0.70465043]
  [0.21772652 0.42135333 0.95384687 0.56420505 0.76072129]
  [0.19121591 0.8368353  0.78370585 0.18859865 0.23311596]]

 [[0.51945375 0.48474529 0.20487417 0.1547462  0.5961797 ]
  [0.39568867 0.60637074 0.46831543 0.9719901  0.95531086]
  [0.83955476 0.46675616 0.40904908 0.64007073 0.69518354]]]


In [40]:
d = a+c
d

array([[[0.31982886, 0.94769592, 0.67816757, 0.61192647, 1.25343402],
        [0.39081817, 1.00998104, 1.14290646, 0.62994482, 1.4523219 ],
        [1.00640688, 0.95224746, 0.82982663, 0.93918164, 0.69753428]],

       [[1.35291539, 1.03056653, 0.7040298 , 0.27782886, 0.91772722],
        [1.37906517, 0.8143673 , 0.53025016, 1.01441384, 1.67458817],
        [1.68271156, 0.83333849, 1.07441577, 1.3728315 , 1.27028499]]])

In [41]:
print(a)
print(d)

[[[0.14191737 0.00136571 0.39849946 0.16524998 0.54878359]
  [0.17309166 0.58862771 0.18905959 0.06573976 0.69160061]
  [0.81519098 0.11541216 0.04612078 0.75058299 0.46441832]]

 [[0.83346164 0.54582124 0.49915563 0.12308266 0.32154751]
  [0.9833765  0.20799656 0.06193473 0.04242374 0.71927731]
  [0.8431568  0.36658233 0.66536669 0.73276077 0.57510144]]]
[[[0.31982886 0.94769592 0.67816757 0.61192647 1.25343402]
  [0.39081817 1.00998104 1.14290646 0.62994482 1.4523219 ]
  [1.00640688 0.95224746 0.82982663 0.93918164 0.69753428]]

 [[1.35291539 1.03056653 0.7040298  0.27782886 0.91772722]
  [1.37906517 0.8143673  0.53025016 1.01441384 1.67458817]
  [1.68271156 0.83333849 1.07441577 1.3728315  1.27028499]]]


In [42]:
e = a*c
e

array([[[0.02524873, 0.00129241, 0.11144759, 0.07381328, 0.38670059],
        [0.03768664, 0.24802025, 0.1803339 , 0.03709071, 0.52611531],
        [0.15587748, 0.09658097, 0.03614513, 0.14155894, 0.10826332]],

       [[0.43294478, 0.26458427, 0.1022641 , 0.01904657, 0.1917001 ],
        [0.38911094, 0.12612303, 0.02900499, 0.04123545, 0.68713343],
        [0.7078763 , 0.17110456, 0.27216763, 0.46901872, 0.39980106]]])

In [44]:
e == a
e.shape == a.shape

True

In [45]:
d_min = d.min()
d_max = d.max()
d_mean = d.mean()

print(d_max,d_mean,d_min)

1.6827115594418194 0.9597185620293062 0.27782885786751466


In [47]:
f = np.empty(d)
f

TypeError: only integer scalar arrays can be converted to a scalar index